<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Medical.Domain\Medical.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\Shared.Application\Shared.Application.csproj" />
    <ProjectReference Include="..\..\Identity\Identity.Application\Identity.Application.csproj" />
  </ItemGroup>
</Project>