<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared.Application\Shared.Application.csproj" />
  </ItemGroup>
</Project>