<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\Shared.Domain\Shared.Domain.csproj" />
    <ProjectReference Include="..\..\Appointments\Appointments.Domain\Appointments.Domain.csproj" />
    <ProjectReference Include="..\..\Insurance\Insurance.Domain\Insurance.Domain.csproj" />
  </ItemGroup>
</Project>