// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApp.Scheduling.Infrastructure.Persistence.DbContext;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Scheduling.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SchedulingDbContext))]
    [Migration("20260928110415_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyApp.Scheduling.Domain.Entities.AppointmentSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_user_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("DoctorScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("doctor_schedule_id");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_user_id");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_appointment_slots_date")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("DoctorScheduleId")
                        .HasDatabaseName("ix_appointment_slots_doctor_schedule_id")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_appointment_slots_status")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("Date", "Status")
                        .HasDatabaseName("ix_appointment_slots_date_status")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("DoctorScheduleId", "Date", "StartTime")
                        .IsUnique()
                        .HasDatabaseName("uq_appointment_slots_schedule_date_time")
                        .HasFilter("is_deleted = false");

                    b.ToTable("appointment_slots", (string)null);
                });

            modelBuilder.Entity("MyApp.Scheduling.Domain.Entities.DoctorSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_user_id");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<Guid>("DoctorHospitalId")
                        .HasColumnType("uuid")
                        .HasColumnName("doctor_hospital_id");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int>("SlotDurationMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30)
                        .HasColumnName("slot_duration_minutes");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_user_id");

                    b.HasKey("Id");

                    b.HasIndex("DoctorHospitalId")
                        .HasDatabaseName("ix_doctor_schedules_doctor_hospital_id")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_doctor_schedules_is_active")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("DoctorHospitalId", "DayOfWeek")
                        .IsUnique()
                        .HasDatabaseName("uq_doctor_schedules_doctor_hospital_day")
                        .HasFilter("is_deleted = false");

                    b.ToTable("doctor_schedules", (string)null);
                });

            modelBuilder.Entity("MyApp.Scheduling.Domain.Entities.DoctorScheduleException", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_user_id");

                    b.Property<Guid>("DoctorScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("doctor_schedule_id");

                    b.Property<DateOnly>("ExceptionDate")
                        .HasColumnType("date")
                        .HasColumnName("exception_date");

                    b.Property<int>("ExceptionType")
                        .HasColumnType("integer")
                        .HasColumnName("exception_type");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<TimeOnly?>("NewEndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("new_end_time");

                    b.Property<TimeOnly?>("NewStartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("new_start_time");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_user_id");

                    b.HasKey("Id");

                    b.HasIndex("DoctorScheduleId")
                        .HasDatabaseName("ix_doctor_schedule_exceptions_doctor_schedule_id")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("ExceptionDate")
                        .HasDatabaseName("ix_doctor_schedule_exceptions_date")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("DoctorScheduleId", "ExceptionDate")
                        .IsUnique()
                        .HasDatabaseName("uq_doctor_schedule_exceptions_schedule_date")
                        .HasFilter("is_deleted = false");

                    b.ToTable("doctor_schedule_exceptions", (string)null);
                });

            modelBuilder.Entity("MyApp.Scheduling.Domain.Entities.AppointmentSlot", b =>
                {
                    b.HasOne("MyApp.Scheduling.Domain.Entities.DoctorSchedule", "DoctorSchedule")
                        .WithMany("AppointmentSlots")
                        .HasForeignKey("DoctorScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DoctorSchedule");
                });

            modelBuilder.Entity("MyApp.Scheduling.Domain.Entities.DoctorScheduleException", b =>
                {
                    b.HasOne("MyApp.Scheduling.Domain.Entities.DoctorSchedule", "DoctorSchedule")
                        .WithMany("Exceptions")
                        .HasForeignKey("DoctorScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoctorSchedule");
                });

            modelBuilder.Entity("MyApp.Scheduling.Domain.Entities.DoctorSchedule", b =>
                {
                    b.Navigation("AppointmentSlots");

                    b.Navigation("Exceptions");
                });
#pragma warning restore 612, 618
        }
    }
}
